spring.datasource.url=jdbc:postgresql://localhost:5432/gen_a102c58a56e9
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
app.secret.admin-api-key=${ADMIN_API_KEY:}
