spring.datasource.url=${APP_DATASOURCE_URL:jdbc:mysql://localhost:3306/gen_b7b8808f756c}
spring.datasource.username=${MYSQL_USERNAME:myuser}
spring.datasource.password=${MYSQL_PASSWORD:mypassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
app.secret.admin-api-key=${ADMIN_API_KEY:local-development-admin-key}
