spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/gen_a102c58a56e9}
spring.datasource.username=${MYSQL_USERNAME:myuser}
spring.datasource.password=${MYSQL_PASSWORD:mypassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
